version: 0.2

phases:
  install:
    commands:
    # printenv
    # pwd
    - mkdir -p /go/src/github.com/weAutomateEverything/smtpHal
    - cp -R * /go/src/github.com/weAutomateEverything/smtpHal/
  pre_build:
    commands:

    finally:

  build:
    commands:
    - go get github.com/weAutomateEverything/smtpHal
    - GOOS=linux go build -ldflags '-linkmode=external' -o ./smtphal github.com/weAutomateEverything/smtpHal
    -
  post_build:
    commands:
    - aws s3 sync ./smtphal "s3://smtphal/smtphal"

    finally:

artifacts:
  files:
  - smtphal
cache:
  paths:
